Edit to fix increacing memory usage
LiskHQ/lisk-db pull request #93
Opened 2023-02-02 18:08 UTC by hrmhatef

### What was the problem?

- This PR resolves memory increment which is described in issue #88
- There is some memory leaks on `instruments` so the issue should be still open.

### How was it solved?

- Implement `close` functions for `ReadWriter` to close the connection.
- Define an empty function for  `StateWriter` to call it from JS.
- Finally implement `close` function for `StateReadWriter` in `state_db.js` to release the memory.

### How was it tested?

- Add a new unit test to check close function in JS.
- Also add a new unit test to check multi_thread usage for StateWriter.
- All tests passed.

### Additional info:

- The result of the `Instruments` for `state_long.js` shows memory usage will be drop when GC is running by JS.
- It depends on the running machine (also the number of iterations for `inner` and `outer` loops) but it should be remain fixed during the execution when the GC is called.

2023-02-02 20:10 UTC, shuse2 requested changes

2023-02-02 20:10 UTC, shuse2 commented on Cargo.toml
> +version = "0.8.5"
shoulnd't this dev dependency?

2023-02-03 07:22 UTC, matjazv approved these changes
Great work @hrmhatef!
This was a tough one.

2023-02-03 08:06 UTC, hrmhatef commented on Cargo.toml
> +version = "0.8.5"
Done.

2023-02-03 08:07 UTC, shuse2 approved these changes

2023-02-03 08:12 UTC, matjazv commented
In `yarn.lock` json5 is degraded from `json5@^2.2.3` to` json5@^2.2.1`.

2023-02-03 08:46 UTC, shuse2 commented
@matjazv I think now it doesn't include the yarn.lock change

2023-02-03 08:46 UTC, merged